#!/bin/sh
# Copyright (c) 2014 Stratio (http://stratio.com)
#

set -e

GROUP='stratio'
USER='stratio'
HOME='/opt/sds'
DIR_INSTALL='/opt/sds/ingestion'  # Add stratio group if it doesn't already exists
if ! getent group ${GROUP} >/dev/null; then
  groupadd ${GROUP}
fi

# Add stratio user if it doesn't already exists
if ! getent passwd ${USER} >/dev/null; then
  [ -d /opt ] || mkdir /opt
  useradd -M -d ${HOME} -g ${GROUP} -s /bin/bash ${USER}
else
  usermod -G $GROUP $USER
fi

chown -R ${USER}:${GROUP} $DIR_INSTALL
chmod 775 $DIR_INSTALL
  
